function updateRotation () {
    mySprite.setImage(scaling.rot(originalImage.clone(), angle))
}
let mySprite: Sprite = null
let originalImage: Image = null
let angle = 0
angle = 0
originalImage = img`
    ....................
    ....................
    ....................
    ....................
    ..............7.....
    ..............7.....
    ...............7....
    .......7777777.7....
    .......7.....7.7....
    .......7.....7.7....
    .......7.....7.7....
    .......7.....7.7....
    .......7.....7.7....
    .......7777777.7....
    ...............7....
    ..............7.....
    ..............7.....
    ....................
    ....................
    ....................
    `
mySprite = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ..............7.....
    ..............7.....
    ...............7....
    .......7777777.7....
    .......7.....7.7....
    .......7.....7.7....
    .......7.....7.7....
    .......7.....7.7....
    .......7.....7.7....
    .......7777777.7....
    ...............7....
    ..............7.....
    ..............7.....
    ....................
    ....................
    ....................
    `, SpriteKind.Player)
mySprite.setStayInScreen(true)
updateRotation()
game.onUpdate(function () {
    if (controller.left.isPressed()) {
        angle += -1
        if (angle < 0) {
            angle = 360
        }
        updateRotation()
    }
    if (controller.right.isPressed()) {
        angle += 1
        if (angle > 360) {
            angle = 0
        }
        updateRotation()
    }
    // spriteutils.setVelocityAtAngle(mySprite, Angle, 50)
    // }
    // } else {
    // spriteutils.setVelocityAtAngle(mySprite, 1 * Angle, 0)
    if (controller.up.isPressed()) {
        spriteutils.setVelocityAtAngle(mySprite, spriteutils.degreesToRadians(angle - 180), 50)
    } else {
        spriteutils.setVelocityAtAngle(mySprite, spriteutils.degreesToRadians(angle), 0)
    }
})
